#!/bin/bash

## This file starts the Jarvis container
echo " _______     __      _      ____   _____ "
echo "|  __ \ \   / //\   | |    / __ \ / ____|"
echo "|_|  | \ \_/ //  \  | |   | |  | | |     "
echo "     | |\   // /\ \ | |   | |  | | |   _ "
echo " ____| | | |/ /  \ \| |___| |__| | |__| |"
echo "|_____/  |_/_/    \_\______\____/ \_____|"
echo ""
echo "https://www.dyalog.com"

echo ""

export JARVIS=/opt/mdyalog/Jarvis
export DYALOG_JARVIS_THREAD=${DYALOG_JARVIS_THREAD-DEBUG}
export DYALOG_JARVIS_PORT=${DYALOG_JARVIS_PORT-8080}
export MAXWS=${MAXWS-256M}
export DYALOG=/opt/mdyalog/18.2/64/unicode/
export WSPATH=/opt/mdyalog/18.2/64/unicode/ws
export TERM=dumb
export APL_TEXTINAPLCORE=${APL_TEXTINAPLCORE-1}
export TRACE_ON_ERROR=${TRACE_ON_ERROR-1}
export LOAD=$JARVIS/Source

export SESSION_FILE="${SESSION_FILE-$DYALOG/default.dse}"

if [ $(ls /app | grep "jarvis.json" 2>/dev/null | wc -l) -eq 1 ]; then
    echo "Application config found in /app/jarvis.json"    
    export JarvisConfig=/app/$(ls /app | grep "jarvis.json")
elif [ $(ls /app 2>/dev/null | wc -l) -gt 0 ]; then
    echo "Application code found in /app."
    CODEL=/app    
else
    echo "No application found in /app. Running with sample app"
    CODEL=$JARVIS/Samples/JSON
fi
export CodeLocation=${CodeLocation-$CODEL}

cd /app

if [ -n "$RIDE_INIT" ]; then
    $DYALOG/dyalog +s -q
else
    $DYALOG/dyalog -s
fi
